spring:
  datasource:
    url: jdbc:mysql://localhost:3306/controle-de-plantas?createDatabaseIfNotExist=true
    username: root
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        lob:
          non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
    org.springframework.web: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
